//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================
#ifndef __INIT_DEVICE_IOLINK_H__
#define __INIT_DEVICE_IOLINK_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
extern void enter_UartMode_from_DefaultMode(void);
extern void enter_DefaultMode_from_UartMode(void);
extern void enter_SioMode_from_UartMode(void);
extern void enter_UartMode_from_SioMode(void);
extern void enter_SioMode_from_DefaultMode(void);
extern void enter_DefaultMode_from_SioMode(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void WDT_0_enter_DefaultMode_from_RESET(void);
extern void PORTS_0_enter_DefaultMode_from_RESET(void);
extern void PORTS_1_enter_DefaultMode_from_RESET(void);
extern void PORTS_2_enter_DefaultMode_from_RESET(void);
extern void PBCFG_0_enter_DefaultMode_from_RESET(void);
extern void CIP51_0_enter_DefaultMode_from_RESET(void);
extern void CLOCK_0_enter_DefaultMode_from_RESET(void);
extern void TIMER_SETUP_0_enter_DefaultMode_from_RESET(void);
extern void SPI_0_enter_DefaultMode_from_RESET(void);
extern void EXTINT_0_enter_DefaultMode_from_RESET(void);
extern void INTERRUPT_0_enter_DefaultMode_from_RESET(void);
extern void PORTS_0_enter_UartMode_from_DefaultMode(void);
extern void PBCFG_0_enter_UartMode_from_DefaultMode(void);
extern void CLU_0_enter_UartMode_from_DefaultMode(void);
extern void CLU_1_enter_UartMode_from_DefaultMode(void);
extern void CLU_3_enter_UartMode_from_DefaultMode(void);
extern void CL_0_enter_UartMode_from_DefaultMode(void);
extern void UARTE_1_enter_UartMode_from_DefaultMode(void);
extern void EXTINT_0_enter_UartMode_from_DefaultMode(void);
extern void INTERRUPT_0_enter_UartMode_from_DefaultMode(void);
extern void PORTS_0_enter_DefaultMode_from_UartMode(void);
extern void PBCFG_0_enter_DefaultMode_from_UartMode(void);
extern void SPI_0_enter_DefaultMode_from_UartMode(void);
extern void EXTINT_0_enter_DefaultMode_from_UartMode(void);
extern void INTERRUPT_0_enter_DefaultMode_from_UartMode(void);
extern void PBCFG_0_enter_SioMode_from_UartMode(void);
extern void INTERRUPT_0_enter_SioMode_from_UartMode(void);
extern void PBCFG_0_enter_UartMode_from_SioMode(void);
extern void CLU_0_enter_UartMode_from_SioMode(void);
extern void CLU_1_enter_UartMode_from_SioMode(void);
extern void CLU_3_enter_UartMode_from_SioMode(void);
extern void CL_0_enter_UartMode_from_SioMode(void);
extern void UARTE_1_enter_UartMode_from_SioMode(void);
extern void INTERRUPT_0_enter_UartMode_from_SioMode(void);
extern void PORTS_0_enter_SioMode_from_DefaultMode(void);
extern void PBCFG_0_enter_SioMode_from_DefaultMode(void);
extern void EXTINT_0_enter_SioMode_from_DefaultMode(void);
extern void INTERRUPT_0_enter_SioMode_from_DefaultMode(void);
extern void PORTS_0_enter_DefaultMode_from_SioMode(void);
extern void PBCFG_0_enter_DefaultMode_from_SioMode(void);
extern void SPI_0_enter_DefaultMode_from_SioMode(void);
extern void EXTINT_0_enter_DefaultMode_from_SioMode(void);
extern void INTERRUPT_0_enter_DefaultMode_from_SioMode(void);
// [Config(Per-Module Mode)Transition Prototypes]$

#endif

